directed: true
multigraph: true
graph: {}
links:
- source: we
  target: UNSPECIFIED_DATA
  key: COLLECT
  text:
  - In the case of inquiries from you outside of an active customer relationship,
    we process the data for sales and advertising purposes.
  - The data is processed on the basis of your consent in accordance with Article
    6(1)(a) GDPR.
  - This website collects and stores data for marketing, market research and optimization
    purposes by using the SalesViewer(r) technology of SalesViewer(r) GmbH.
  - We use this data to send the newsletter.
  purposes:
    advertising:
    - for marketing, market research and optimization purposes
    - for sales and advertising purposes
    - to send the newsletter
    analytics:
    - for marketing, market research and optimization purposes
    services:
    - to send the newsletter
- source: we
  target: aforementioned datum
  key: COLLECT
  text:
  - We process the aforementioned data for the operation of our website and for the
    fulfillment of contractual obligations towards our customers or the protection
    of our legitimate interests.
  purposes:
    legal:
    - for the operation of our website and for the fulfillment of contractual obligations
      towards our customers or the protection of our legitimate interests
    security:
    - for the operation of our website and for the fulfillment of contractual obligations
      towards our customers or the protection of our legitimate interests
    services:
    - for the operation of our website and for the fulfillment of contractual obligations
      towards our customers or the protection of our legitimate interests
- source: we
  target: as little datum as
  key: COLLECT
  text:
  - For this reason, we collect as little data as possible from you.
  purposes: {}
- source: we
  target: call google web fonts
  key: COLLECT
  text:
  - We use so-called Google Web Fonts on our website.
  purposes: {}
- source: we
  target: contact form
  key: COLLECT
  text:
  - Contact form
  - We need this information to process your request, to address you correctly and
    to send you an answer.
  purposes:
    services:
    - to process your request, to address you correctly and to send you an answer
- source: we
  target: cookie / pixel tag
  key: COLLECT
  text:
  - The law states that we can store cookies on your device if they are strictly necessary
    for the operation of this website.
  - This site uses different types of cookies.
  - This website uses cookies.
  - We use cookies to personalize content and ads, provide social media features,
    and analyze our traffic.
  purposes:
    advertising:
    - to personalize content and ads, provide social media features, and analyze our
      traffic
    analytics:
    - to personalize content and ads, provide social media features, and analyze our
      traffic
    services:
    - to personalize content and ads, provide social media features, and analyze our
      traffic
- source: we
  target: datum be
  key: COLLECT
  text:
  - In connection with submissions and inquiries, we only process data that is necessary
    to communicate with you and to properly document the business processes.
  purposes: {}
- source: we
  target: datum we receive from you
  key: COLLECT
  text:
  - We will only pass on the data we receive from you to third parties if you have
    expressly consented to this or if we are obliged to do so by law or on the basis
    of a court decision.
  purposes: {}
- source: we
  target: email address
  key: COLLECT
  text:
  - For organizational reasons, we must collect your first and last name, telephone
    number and email address in advance of the event in order to perform our duties
    in accordance with Article 6(1)(e) and (3)(b) GDPR in conjunction with Section
    3 BDSG.
  - In addition to the voluntary information in the respective form, we only process
    your email address.
  purposes:
    legal:
    - in order to perform our duties in accordance with Article 6(1)(e) and (3)(b)
      GDPR in conjunction with Section 3 BDSG
    services:
    - For organizational reasons
- source: we
  target: information about use of website
  key: COLLECT
  text:
  - We also share information about your use of our website with our social media,
    advertising and analytics partners, who may combine it with other information
    that you have provided to them or that they have collected from your use of their
    services
  purposes: {}
- source: we
  target: inquiry receive via contact form on website
  key: COLLECT
  text:
  - Inquiries received via the contact form on our website are processed electronically
    by us in order to answer your inquiry.
  purposes: {}
- source: we
  target: person name
  key: COLLECT
  text:
  - For organizational reasons, we must collect your first and last name, telephone
    number and email address in advance of the event in order to perform our duties
    in accordance with Article 6(1)(e) and (3)(b) GDPR in conjunction with Section
    3 BDSG.
  purposes:
    legal:
    - in order to perform our duties in accordance with Article 6(1)(e) and (3)(b)
      GDPR in conjunction with Section 3 BDSG
    services:
    - For organizational reasons
- source: we
  target: personal information
  key: COLLECT
  text:
  - 'In order to be able to offer you our website and the associated services, we
    process personal data on the basis of the following legal bases:'
  purposes:
    legal:
    - for the fulfillment of a legal obligation (Art. 6 para. 1 lit. c) GDPR
- source: we
  target: phone number
  key: COLLECT
  text:
  - For organizational reasons, we must collect your first and last name, telephone
    number and email address in advance of the event in order to perform our duties
    in accordance with Article 6(1)(e) and (3)(b) GDPR in conjunction with Section
    3 BDSG.
  purposes:
    legal:
    - in order to perform our duties in accordance with Article 6(1)(e) and (3)(b)
      GDPR in conjunction with Section 3 BDSG
    services:
    - For organizational reasons
- source: we
  target: ssl encryption
  key: COLLECT
  text:
  - This site uses SSL or TLS encryption for security reasons and to protect the transmission
    of confidential content, such as orders or inquiries that you send to us as the
    site operator.
  purposes:
    security:
    - for security reasons and to protect the transmission of confidential content,
      such as orders or inquiries that you send to us as the site operator
- source: we
  target: visitor action pixel from facebook
  key: COLLECT
  text:
  - Our website uses the visitor action pixel from Facebook, Facebook Inc, 1601 S.
    California Ave, Palo Alto, CA 94304, USA ("Facebook") to measure conversions.
  purposes:
    analytics:
    - to measure conversions
- source: Big Data Perspective
  target: UNSPECIFIED_DATA
  key: COLLECT
  text:
  - In addition, Perspective Software GmbH processes further data, some of which may
    also be personal data, in order to provide its services, in particular for the
    operation of the Mobile Funnel.
  purposes:
    services:
    - in order to provide its services, in particular for the operation of the Mobile
      Funnel
- source: Facebook
  target: UNSPECIFIED_DATA
  key: COLLECT
  text:
  - However, the data is stored and processed by Facebook so that a connection to
    the respective user profile is possible and Facebook can use the data for its
    own advertising purposes in accordance with the Facebook Data Usage Policy.
  purposes: {}
- source: Google
  target: UNSPECIFIED_DATA
  key: COLLECT
  text:
  - Google uses the following data to check whether you are a human or a computer
    IP address of the end device used, the website that you visit on our site and
    on which the captcha is integrated, the date and duration of the visit, the identification
    data of the browser and operating system type used, Google account if you are
    logged in to Google, mouse movements on the reCaptcha areas and tasks in which
    you have to identify images.
  purposes:
    analytics:
    - to check whether you are a human or a computer IP address of the end device
      used, the website that you visit on our site and on which the captcha is integrated,
      the date and duration of the visit, the identification data of the browser and
      operating system type used, Google account if you are logged in to Google, mouse
      movements on the reCaptcha areas and tasks in which you have to identify images
    services:
    - to check whether you are a human or a computer IP address of the end device
      used, the website that you visit on our site and on which the captcha is integrated,
      the date and duration of the visit, the identification data of the browser and
      operating system type used, Google account if you are logged in to Google, mouse
      movements on the reCaptcha areas and tasks in which you have to identify images
- source: Google
  target: cookie / pixel tag
  key: COLLECT
  text:
  - Google Analytics uses "cookies", which are text files placed on your computer,
    to help the website analyze how users use the site.
  - The information generated by the cookie about your use of this website is usually
    transmitted to a Google server in the USA and stored there.
  purposes:
    analytics:
    - to help the website analyze how users use the site
- source: Google
  target: ip address
  key: COLLECT
  text:
  - Google will use this information on behalf of the operator of this website for
    the purpose of evaluating your use of the website, compiling reports on website
    activity and providing other services relating to website activity and internet
    usage to the website operator.
  - Only in exceptional cases will the full IP address be transmitted to a Google
    server in the USA and truncated there.
  purposes:
    analytics:
    - for the purpose of evaluating your use of the website, compiling reports on
      website activity and providing other services relating to website activity and
      internet usage to the website operator
- source: UNSPECIFIED_ACTOR
  target: datum log
  key: COLLECT
  text:
  - Data logged when accessing the Linkando GmbH website will only be transmitted
    to third parties if we are legally obliged to do so or if disclosure is necessary
    for legal or criminal prosecution in the event of attacks on communications technology.
  purposes: {}
- source: UNSPECIFIED_ACTOR
  target: datum we receive from you
  key: COLLECT
  text:
  - We will only pass on the data we receive from you to third parties if you have
    expressly consented to this or if we are obliged to do so by law or on the basis
    of a court decision.
  purposes: {}
- source: advertiser
  target: information about use of website
  key: COLLECT
  text:
  - We also share information about your use of our website with our social media,
    advertising and analytics partners, who may combine it with other information
    that you have provided to them or that they have collected from your use of their
    services
  purposes: {}
- source: analytic provider
  target: information about use of website
  key: COLLECT
  text:
  - We also share information about your use of our website with our social media,
    advertising and analytics partners, who may combine it with other information
    that you have provided to them or that they have collected from your use of their
    services
  purposes: {}
- source: internet browser
  target: technical information
  key: COLLECT
  text:
  - In order to set up the audio and video conference, technical information is transmitted
    to Nexmo Inc. by the Internet browser (e.g. IP address, browser type, set language,
    date and time) and, if necessary, used and statistically evaluated for the procedure.
  purposes:
    services:
    - In order to set up the audio and video conference
- source: leadinfo
  target: UNSPECIFIED_DATA
  key: COLLECT
  text:
  - If you opt out, your data will no longer be collected by Leadinfo.
  purposes: {}
- source: linkando
  target: personal information
  key: COLLECT
  text:
  - Linkando processes your personal data in order to provide the product to your
    organization/association and to you, as well as for Linkando's legitimate business
    operations in connection with the provision of the product.
  purposes:
    services:
    - in order to provide the product to your organization/association and to you,
      as well as for Linkando's legitimate business operations in connection with
      the provision of the product
- source: matomo
  target: cookie / pixel tag
  key: COLLECT
  text:
  - Matomo stores cookies on your end device that enable your use of our website to
    be analyzed.
  purposes: {}
- source: nexmo inc.
  target: technical information
  key: COLLECT
  text:
  - In order to set up the audio and video conference, technical information is transmitted
    to Nexmo Inc. by the Internet browser (e.g. IP address, browser type, set language,
    date and time) and, if necessary, used and statistically evaluated for the procedure.
  purposes:
    services:
    - In order to set up the audio and video conference
- source: organization affiliate with
  target: diagnostic datum
  key: COLLECT
  text:
  - 'If you use a Linkando product with an account provided by an organization you
    are affiliated with, such as your work or association account, that organization
    may: Access and process your data, including interaction data, diagnostic data
    and the content of your messages and files associated with your Linkando product
    and product accounts.'
  purposes: {}
- source: organization affiliate with
  target: interaction datum
  key: COLLECT
  text:
  - 'If you use a Linkando product with an account provided by an organization you
    are affiliated with, such as your work or association account, that organization
    may: Access and process your data, including interaction data, diagnostic data
    and the content of your messages and files associated with your Linkando product
    and product accounts.'
  purposes: {}
- source: social media
  target: information about use of website
  key: COLLECT
  text:
  - We also share information about your use of our website with our social media,
    advertising and analytics partners, who may combine it with other information
    that you have provided to them or that they have collected from your use of their
    services
  purposes: {}
- source: stetic
  target: cookie / pixel tag
  key: COLLECT
  text:
  - Stetic uses so-called "cookies".
  purposes: {}
- source: weglot
  target: UNSPECIFIED_DATA
  key: COLLECT
  text:
  - Weglot then receives the information that you have visited this website with your
    IP address.
  purposes: {}
- source: youtube
  target: datum about you as user
  key: COLLECT
  text:
  - These are all integrated in "extended data protection mode", i.e. no data about
    you as a user is transferred to YouTube if you do not play the videos.
  purposes: {}
- source: personal information
  target: phone number
  key: SUBSUM
  text:
  - 'The following personal data is collected when an appointment is booked: Phone
    number'
nodes:
- type: ACTOR
  id: Big Data Perspective
- type: ACTOR
  id: Facebook
- type: ACTOR
  id: Google
- type: ACTOR
  id: UNSPECIFIED_ACTOR
- type: ACTOR
  id: advertiser
- type: ACTOR
  id: analytic provider
- type: ACTOR
  id: internet browser
- type: ACTOR
  id: leadinfo
- type: ACTOR
  id: linkando
- type: ACTOR
  id: matomo
- type: ACTOR
  id: nexmo inc.
- type: ACTOR
  id: organization affiliate with
- type: ACTOR
  id: social media
- type: ACTOR
  id: stetic
- type: ACTOR
  id: we
- type: ACTOR
  id: weglot
- type: ACTOR
  id: youtube
- type: DATA
  id: UNSPECIFIED_DATA
- type: DATA
  id: aforementioned datum
- type: DATA
  id: as little datum as
- type: DATA
  id: call google web fonts
- type: DATA
  id: contact form
- type: DATA
  id: cookie / pixel tag
- type: DATA
  id: datum about you as user
- type: DATA
  id: datum be
- type: DATA
  id: datum log
- type: DATA
  id: datum we receive from you
- type: DATA
  id: diagnostic datum
- type: DATA
  id: email address
- type: DATA
  id: information about use of website
- type: DATA
  id: inquiry receive via contact form on website
- type: DATA
  id: interaction datum
- type: DATA
  id: ip address
- type: DATA
  id: person name
- type: DATA
  id: personal information
- type: DATA
  id: phone number
- type: DATA
  id: ssl encryption
- type: DATA
  id: technical information
- type: DATA
  id: visitor action pixel from facebook
